Traceback (most recent call last):
  File "F:/off-policy/offpolicy/scripts/train/train_mpe.py", line 196, in <module>
    main(sys.argv[1:])
  File "F:/off-policy/offpolicy/scripts/train/train_mpe.py", line 179, in main
    runner = Runner(config=config)
  File "F:\off-policy\offpolicy\runner\mlp\mpe_runner.py", line 12, in __init__
    super(MPERunner, self).__init__(config)
  File "F:\off-policy\offpolicy\runner\mlp\base_runner.py", line 156, in __init__
    self.buffer = MlpReplayBuffer(self.policy_info,
  File "F:\off-policy\offpolicy\utils\mlp_buffer.py", line 26, in __init__
    self.policy_buffers = {p_id: MlpPolicyBuffer(buffer_size,
  File "F:\off-policy\offpolicy\utils\mlp_buffer.py", line 26, in <dictcomp>
    self.policy_buffers = {p_id: MlpPolicyBuffer(buffer_size,
  File "F:\off-policy\offpolicy\utils\mlp_buffer.py", line 144, in __init__
    self.next_obs = np.zeros_like(self.obs, dtype=np.float32)
  File "<__array_function__ internals>", line 180, in zeros_like
  File "E:\Anaconda\lib\site-packages\numpy\core\numeric.py", line 138, in zeros_like
    res = empty_like(a, dtype=dtype, order=order, subok=subok, shape=shape)
  File "<__array_function__ internals>", line 180, in empty_like
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 191. MiB for an array with shape (5000, 1, 10000) and data type float32
reset111111111111111111
buffer size is 5000 1 (10000,)
self.use_same_share_obs False
share_obs_shape (10000,)